// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SindiOps.API.Infrastructure.Data;

#nullable disable

namespace SindiOps.API.Migrations
{
    [DbContext(typeof(SindiOpsDbContext))]
    [Migration("20260923154753_OrdemItemSolicitacaoCompra")]
    partial class OrdemItemSolicitacaoCompra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SindiOps.API.Entities.Bloco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.ToTable("blocos", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.Condominio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataEleicao")
                        .HasColumnType("date")
                        .HasColumnName("data_eleicao");

                    b.Property<string>("EnderecoBairro")
                        .HasColumnType("text")
                        .HasColumnName("endereco_bairro");

                    b.Property<string>("EnderecoCep")
                        .HasColumnType("text")
                        .HasColumnName("endereco_cep");

                    b.Property<string>("EnderecoCidade")
                        .HasColumnType("text")
                        .HasColumnName("endereco_cidade");

                    b.Property<string>("EnderecoNumero")
                        .HasColumnType("text")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("EnderecoRua")
                        .HasColumnType("text")
                        .HasColumnName("endereco_rua");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("SindicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sindico_id");

                    b.Property<DateOnly?>("VencimentoMandato")
                        .HasColumnType("date")
                        .HasColumnName("vencimento_mandato");

                    b.HasKey("Id");

                    b.HasIndex("SindicoId");

                    b.ToTable("condominios", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CondicoesRenovacao")
                        .HasColumnType("text")
                        .HasColumnName("condicoes_renovacao");

                    b.Property<string>("CondicoesRescisao")
                        .HasColumnType("text")
                        .HasColumnName("condicoes_rescisao");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("IndiceReajuste")
                        .HasColumnType("text")
                        .HasColumnName("indice_reajuste");

                    b.Property<string>("NomeContato")
                        .HasColumnType("text")
                        .HasColumnName("nome_contato");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("TelefoneContato")
                        .HasColumnType("text")
                        .HasColumnName("telefone_contato");

                    b.Property<string>("TipoServico")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_servico");

                    b.Property<decimal?>("ValorMensal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_mensal");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("Status");

                    b.HasIndex("CondominioId", "Status");

                    b.ToTable("contratos", null, t =>
                        {
                            t.HasCheckConstraint("ck_contratos_status", "status IN ('active', 'expiring', 'expired', 'cancelled')");

                            t.HasCheckConstraint("ck_contratos_tipo_servico", "tipo_servico IN ('administradora','garantidora','gas','telefonia','internet','terceirizada','juridico','manutencao_elevador','manutencao_jardim','gestao_residuos','outro')");

                            t.HasCheckConstraint("ck_contratos_valor_mensal", "valor_mensal IS NULL OR valor_mensal > 0");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.Cotacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("NomeContato")
                        .HasColumnType("text")
                        .HasColumnName("nome_contato");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("text")
                        .HasColumnName("nome_empresa");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("text")
                        .HasColumnName("nome_responsavel");

                    b.Property<bool>("Selecionada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("selecionada");

                    b.Property<Guid>("SolicitacaoCompraId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_compra_id");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("SolicitacaoCompraId")
                        .IsUnique()
                        .HasDatabaseName("ix_cotacoes_selecionada_unica")
                        .HasFilter("selecionada = true");

                    b.ToTable("cotacoes", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.CotacaoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CotacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cotacao_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId");

                    b.HasIndex("ItemId");

                    b.HasIndex("CotacaoId", "ItemId")
                        .IsUnique();

                    b.ToTable("cotacao_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_cotacao_itens_valor_total", "valor_total > 0");

                            t.HasCheckConstraint("ck_cotacao_itens_valor_unitario", "valor_unitario > 0");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assunto");

                    b.Property<string>("CorpoResolvido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo_resolvido");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EmailDestinatario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_destinatario");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<Guid>("EnviadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("enviado_por_id");

                    b.Property<Guid>("MoradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("morador_id");

                    b.Property<Guid?>("OcorrenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ocorrencia_id");

                    b.Property<Guid>("SindicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sindico_id");

                    b.Property<string>("StatusEntrega")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("sent")
                        .HasColumnName("status_entrega");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<decimal?>("ValorMulta")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_multa");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorId");

                    b.HasIndex("MoradorId");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("SindicoId");

                    b.HasIndex("StatusEntrega");

                    b.HasIndex("TemplateId");

                    b.ToTable("email_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_logs_status_entrega", "status_entrega IN ('sent', 'delivered', 'failed')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assunto");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("corpo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<Guid>("SindicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("SindicoId");

                    b.ToTable("email_templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_templates_tipo", "tipo IN ('advertencia', 'multa', 'notificacao_ocorrencia', 'comunicado_geral', 'notificacao_manutencao')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EnderecoBairro")
                        .HasColumnType("text")
                        .HasColumnName("endereco_bairro");

                    b.Property<string>("EnderecoCep")
                        .HasColumnType("text")
                        .HasColumnName("endereco_cep");

                    b.Property<string>("EnderecoCidade")
                        .HasColumnType("text")
                        .HasColumnName("endereco_cidade");

                    b.Property<string>("EnderecoNumero")
                        .HasColumnType("text")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("EnderecoRua")
                        .HasColumnType("text")
                        .HasColumnName("endereco_rua");

                    b.Property<string>("Instagram")
                        .HasColumnType("text")
                        .HasColumnName("instagram");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("NomeContato")
                        .HasColumnType("text")
                        .HasColumnName("nome_contato");

                    b.Property<Guid>("SindicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sindico_id");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("cnpj IS NOT NULL");

                    b.HasIndex("SindicoId");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.ManutencaoObrigatoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ok")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateOnly?>("UltimaRealizacao")
                        .HasColumnType("date")
                        .HasColumnName("ultima_realizacao");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("Status");

                    b.HasIndex("CondominioId", "DataVencimento");

                    b.ToTable("manutencoes_obrigatorias", null, t =>
                        {
                            t.HasCheckConstraint("ck_manutencoes_status", "status IN ('ok', 'upcoming', 'overdue')");

                            t.HasCheckConstraint("ck_manutencoes_tipo", "tipo IN ('dedetizacao','para_raios','seguro','limpeza_caixa_agua','caixa_gordura_esgoto','extintores','cvcb','calhas_telhado','ppra','pcmso','pgr')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.MidiaOcorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EnviadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("enviado_por_id");

                    b.Property<Guid>("OcorrenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ocorrencia_id");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_arquivo");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_arquivo");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorId");

                    b.HasIndex("OcorrenciaId");

                    b.ToTable("midias_ocorrencia", null, t =>
                        {
                            t.HasCheckConstraint("ck_midias_tipo_arquivo", "tipo_arquivo IN ('image', 'video')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.Morador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletado_em");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("papel");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("UnidadeId")
                        .IsUnique()
                        .HasDatabaseName("ix_moradores_proprietario_unico")
                        .HasFilter("papel = 'proprietario' AND deletado_em IS NULL");

                    b.HasIndex("UnidadeId", "PessoaId")
                        .IsUnique()
                        .HasDatabaseName("ix_moradores_unidade_pessoa")
                        .HasFilter("deletado_em IS NULL");

                    b.ToTable("moradores", null, t =>
                        {
                            t.HasCheckConstraint("ck_moradores_papel", "papel IN ('proprietario', 'inquilino', 'ocupante')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.Ocorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid?>("BlocoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloco_id");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("MoradorId")
                        .HasColumnType("uuid")
                        .HasColumnName("morador_id");

                    b.Property<DateTime>("OcorreuEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorreu_em");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origem");

                    b.Property<Guid>("RegistradoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("nova")
                        .HasColumnName("status");

                    b.Property<string>("TipoLocal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_local");

                    b.Property<string>("TipoOcorrencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_ocorrencia");

                    b.Property<Guid?>("UnidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidade_id");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId");

                    b.HasIndex("CondominioId");

                    b.HasIndex("MoradorId");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("UnidadeId");

                    b.HasIndex("CondominioId", "OcorreuEm");

                    b.HasIndex("CondominioId", "Status");

                    b.ToTable("ocorrencias", null, t =>
                        {
                            t.HasCheckConstraint("ck_ocorrencias_origem", "origem IN ('reclamacao_morador', 'reclamacao_funcionario', 'reclamacao_terceiros', 'fora_de_norma')");

                            t.HasCheckConstraint("ck_ocorrencias_status", "status IN ('nova', 'em_andamento', 'finalizada', 'cancelada')");

                            t.HasCheckConstraint("ck_ocorrencias_tipo_local", "tipo_local IS NULL OR tipo_local IN ('area_comum','estacionamento','portaria','jardim','salao_festas','hall','corredores','vizinhos','outro')");

                            t.HasCheckConstraint("ck_ocorrencias_tipo_ocorrencia", "tipo_ocorrencia IS NULL OR tipo_ocorrencia IN ('barulho','pets','garagem','alteracao_fachada','objetos_corredores','objetos_janelas_sacadas','outro')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.ToTable("pessoas", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.ServicoFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("servicos_fornecedor", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.Solicitacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SolicitadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitado_por_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("nova")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CondominioId");

                    b.HasIndex("SolicitadoPorId");

                    b.HasIndex("CondominioId", "Status");

                    b.ToTable("solicitacoes", null, t =>
                        {
                            t.HasCheckConstraint("ck_solicitacoes_status", "status IN ('nova', 'em_andamento', 'finalizada', 'cancelada')");

                            t.HasCheckConstraint("ck_solicitacoes_tipo", "tipo IN ('compra', 'manutencao')");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoCompraItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<bool>("EReposicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("e_reposicao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("SolicitacaoCompraId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitacao_compra_id");

                    b.Property<string>("Unidade")
                        .HasColumnType("text")
                        .HasColumnName("unidade");

                    b.HasKey("Id");

                    b.HasIndex("SolicitacaoCompraId");

                    b.ToTable("solicitacao_compra_itens", null, t =>
                        {
                            t.HasCheckConstraint("ck_sol_compra_item_categoria", "categoria IN ('papelaria', 'mat_construcao', 'mat_limpeza', 'mat_especifico')");

                            t.HasCheckConstraint("ck_sol_compra_item_ordem", "ordem >= 0");

                            t.HasCheckConstraint("ck_sol_compra_item_quantidade", "quantidade > 0");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.Unidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BlocoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bloco_id");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.HasIndex("BlocoId");

                    b.HasIndex("CondominioId");

                    b.HasIndex("BlocoId", "Numero")
                        .IsUnique();

                    b.ToTable("unidades", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("uuid")
                        .HasColumnName("pessoa_id");

                    b.Property<Guid?>("SindicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("sindico_id");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId")
                        .IsUnique();

                    b.HasIndex("SindicoId");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuarios_cargo", "cargo IN ('sindico', 'secretario', 'zelador', 'porteiro', 'outro')");

                            t.HasCheckConstraint("ck_usuarios_sindico_carteira", "(cargo = 'sindico' AND sindico_id IS NULL) OR (cargo <> 'sindico' AND sindico_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.UsuarioCondominio", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("CondominioId")
                        .HasColumnType("uuid")
                        .HasColumnName("condominio_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UsuarioId", "CondominioId");

                    b.HasIndex("CondominioId");

                    b.ToTable("usuario_condominios", (string)null);
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoCompra", b =>
                {
                    b.HasBaseType("SindiOps.API.Entities.Solicitacao");

                    b.Property<Guid?>("AprovadoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("aprovado_por_id");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text")
                        .HasColumnName("justificativa");

                    b.Property<string>("TipoAprovacao")
                        .HasColumnType("text")
                        .HasColumnName("tipo_aprovacao");

                    b.HasIndex("AprovadoPorId");

                    b.ToTable("solicitacoes_compra", null, t =>
                        {
                            t.HasCheckConstraint("ck_solicitacoes_status", "status IN ('nova', 'em_andamento', 'finalizada', 'cancelada')");

                            t.HasCheckConstraint("ck_solicitacoes_tipo", "tipo IN ('compra', 'manutencao')");

                            t.HasCheckConstraint("ck_sol_compra_tipo_aprovacao", "tipo_aprovacao IS NULL OR tipo_aprovacao IN ('sindico', 'conselho', 'assembleia')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoManutencao", b =>
                {
                    b.HasBaseType("SindiOps.API.Entities.Solicitacao");

                    b.Property<DateOnly?>("DataConclusao")
                        .HasColumnType("date")
                        .HasColumnName("data_conclusao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Local")
                        .HasColumnType("text")
                        .HasColumnName("local");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text")
                        .HasColumnName("responsavel");

                    b.Property<string>("TipoManutencao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasIndex("FornecedorId");

                    b.ToTable("solicitacoes_manutencao", null, t =>
                        {
                            t.HasCheckConstraint("ck_solicitacoes_status", "status IN ('nova', 'em_andamento', 'finalizada', 'cancelada')");

                            t.HasCheckConstraint("ck_solicitacoes_tipo", "tipo IN ('compra', 'manutencao')");

                            t.HasCheckConstraint("ck_sol_manutencao_responsavel", "responsavel IS NULL OR responsavel IN ('fornecedor', 'zelador')");

                            t.HasCheckConstraint("ck_sol_manutencao_tipo", "tipo IN ('obra_civil','pintura','serralheria','eletrica','hidraulica','cameras','portas_portoes','jardim','esgoto','caixa_gordura','outro')");
                        });
                });

            modelBuilder.Entity("SindiOps.API.Entities.Bloco", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Condominio", "Condominio")
                        .WithMany("Blocos")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Condominio", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Usuario", "Sindico")
                        .WithMany("Condominios")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Contrato", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Condominio", "Condominio")
                        .WithMany("Contratos")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Fornecedor", "Fornecedor")
                        .WithMany("Contratos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominio");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Cotacao", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SindiOps.API.Entities.SolicitacaoCompra", "SolicitacaoCompra")
                        .WithMany("Cotacoes")
                        .HasForeignKey("SolicitacaoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("SolicitacaoCompra");
                });

            modelBuilder.Entity("SindiOps.API.Entities.CotacaoItem", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Cotacao", "Cotacao")
                        .WithMany("Itens")
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.SolicitacaoCompraItem", "Item")
                        .WithMany("CotacaoItens")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cotacao");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SindiOps.API.Entities.EmailLog", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Morador", "Morador")
                        .WithMany("EmailLogs")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Ocorrencia", "Ocorrencia")
                        .WithMany("EmailLogs")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SindiOps.API.Entities.Usuario", "Sindico")
                        .WithMany("EmailLogs")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.EmailTemplate", "Template")
                        .WithMany("EmailLogs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EnviadoPor");

                    b.Navigation("Morador");

                    b.Navigation("Ocorrencia");

                    b.Navigation("Sindico");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SindiOps.API.Entities.EmailTemplate", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Usuario", "Sindico")
                        .WithMany("EmailTemplates")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Fornecedor", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Usuario", "Sindico")
                        .WithMany("Fornecedores")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("SindiOps.API.Entities.ManutencaoObrigatoria", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Condominio", "Condominio")
                        .WithMany("ManutencoesObrigatorias")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("SindiOps.API.Entities.MidiaOcorrencia", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Usuario", "EnviadoPor")
                        .WithMany()
                        .HasForeignKey("EnviadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Ocorrencia", "Ocorrencia")
                        .WithMany("Midias")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnviadoPor");

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Morador", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Pessoa", "Pessoa")
                        .WithMany("Moradores")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Unidade", "Unidade")
                        .WithMany("Moradores")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Ocorrencia", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Bloco", "Bloco")
                        .WithMany()
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SindiOps.API.Entities.Condominio", "Condominio")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Morador", "Morador")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("MoradorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SindiOps.API.Entities.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bloco");

                    b.Navigation("Condominio");

                    b.Navigation("Morador");

                    b.Navigation("RegistradoPor");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("SindiOps.API.Entities.ServicoFornecedor", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Fornecedor", "Fornecedor")
                        .WithMany("Servicos")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Solicitacao", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Condominio", "Condominio")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Usuario", "SolicitadoPor")
                        .WithMany()
                        .HasForeignKey("SolicitadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condominio");

                    b.Navigation("SolicitadoPor");
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoCompraItem", b =>
                {
                    b.HasOne("SindiOps.API.Entities.SolicitacaoCompra", "SolicitacaoCompra")
                        .WithMany("Itens")
                        .HasForeignKey("SolicitacaoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitacaoCompra");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Unidade", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Bloco", "Bloco")
                        .WithMany("Unidades")
                        .HasForeignKey("BlocoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Condominio", "Condominio")
                        .WithMany("Unidades")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bloco");

                    b.Navigation("Condominio");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Usuario", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("SindiOps.API.Entities.Usuario", "PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Usuario", "Sindico")
                        .WithMany("Equipe")
                        .HasForeignKey("SindicoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pessoa");

                    b.Navigation("Sindico");
                });

            modelBuilder.Entity("SindiOps.API.Entities.UsuarioCondominio", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Condominio", "Condominio")
                        .WithMany("UsuariosAcesso")
                        .HasForeignKey("CondominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SindiOps.API.Entities.Usuario", "Usuario")
                        .WithMany("CondominiosAcesso")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condominio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoCompra", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Usuario", "AprovadoPor")
                        .WithMany()
                        .HasForeignKey("AprovadoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SindiOps.API.Entities.Solicitacao", null)
                        .WithOne()
                        .HasForeignKey("SindiOps.API.Entities.SolicitacaoCompra", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AprovadoPor");
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoManutencao", b =>
                {
                    b.HasOne("SindiOps.API.Entities.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SindiOps.API.Entities.Solicitacao", null)
                        .WithOne()
                        .HasForeignKey("SindiOps.API.Entities.SolicitacaoManutencao", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Bloco", b =>
                {
                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Condominio", b =>
                {
                    b.Navigation("Blocos");

                    b.Navigation("Contratos");

                    b.Navigation("ManutencoesObrigatorias");

                    b.Navigation("Ocorrencias");

                    b.Navigation("Solicitacoes");

                    b.Navigation("Unidades");

                    b.Navigation("UsuariosAcesso");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Cotacao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SindiOps.API.Entities.EmailTemplate", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Fornecedor", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Morador", b =>
                {
                    b.Navigation("EmailLogs");

                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Ocorrencia", b =>
                {
                    b.Navigation("EmailLogs");

                    b.Navigation("Midias");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Pessoa", b =>
                {
                    b.Navigation("Moradores");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoCompraItem", b =>
                {
                    b.Navigation("CotacaoItens");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Unidade", b =>
                {
                    b.Navigation("Moradores");
                });

            modelBuilder.Entity("SindiOps.API.Entities.Usuario", b =>
                {
                    b.Navigation("Condominios");

                    b.Navigation("CondominiosAcesso");

                    b.Navigation("EmailLogs");

                    b.Navigation("EmailTemplates");

                    b.Navigation("Equipe");

                    b.Navigation("Fornecedores");
                });

            modelBuilder.Entity("SindiOps.API.Entities.SolicitacaoCompra", b =>
                {
                    b.Navigation("Cotacoes");

                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
